server:
  port: 8686

spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
 
  application:
    name: blood-donor-mvc
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka    
      
logging:
  level:
    org:
      springframework:
        web: DEBUG      